INSERT INTO `oxconfig` (`OXID`, `OXSHOPID`, `OXMODULE`, `OXVARNAME`, `OXVARTYPE`, `OXVARVALUE`, `OXTIMESTAMP`)
VALUES (uuid(), 1, 'theme:o3-theme', 'sGATrackingId', 'str', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showWishlist', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sFaviconSvgFile', 'str', 'icon.svg', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sCatPromotionsize', 'str', '370*107', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sCatThumbnailsize', 'str', '1296*500', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sTwitterUrl', 'str', 'https://twitter.com', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sFacebookUrl', 'str', 'https://www.facebook.com', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sIconsize', 'str', '114*114', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sShippingDaysOnStock', 'str', '3', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sInstagramUrl', 'str', 'https://instagram.com', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sSliderInterval', 'str', '5000', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blUseGAPageTracker', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sSliderSlideFade', 'select', 'fade', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showPriceAlarm', 'bool', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sZoomImageSize', 'str', '665*665', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blFooterColor', 'str', '#01071C', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showVouchers', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blFooterShowLinks', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sSliderSpeed', 'str', '400', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_articleAmountMax', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sDefaultListDisplayType', 'select', 'grid', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blHomeLink', 'bool', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showGiftWrapping', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sShoppingLanguage', 'str', 'de', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blUseGAEcommerceTracking', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sGoogleVendorId', 'str', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blShowFilters', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blFooterShowNews', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sYouTubeUrl', 'str', 'https://www.youtube.com', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showListmania', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showCompareList', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blSecondaryColor', 'str', '#F2F6FF', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sEmailLogo', 'str', 'logo.svg', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sPageLanguage', 'str', 'de_DE', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sShippingDaysNotOnStock', 'str', '5', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'aDetailImageSizes', 'aarr',
        'a:12:{s:6:"oxpic1";s:7:"752*633";s:6:"oxpic2";s:7:"752*633";...}', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'bl_showManufacturer', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sFaviconIcoFile', 'str', 'favicon.ico', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sCatIconsize', 'str', '168*100', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blUseGoogleTS', 'bool', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blFooterShowHelp', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blGAAnonymizeIPs', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blShowBirthdayFields', 'bool', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sFavicon192PngFile', 'str', 'icon-192.png', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'aNrofCatArticles', 'arr',
        'a:4:{i:0;s:2:"10";i:1;s:2:"20";i:2;s:2:"50";i:3;s:3:"100";}', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blEmailsShowProductPictures', 'bool', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'activateJquery', 'bool', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sLogoFile', 'str', 'logo.svg', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sDeliveryDaysNotOnStock', 'str', '14', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sManufacturerIconsize', 'str', '100*100', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blFooterShowNewsletter', 'bool', '1', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sGoogleMapsAddr', 'str', 'O3-Shop, Musterstraße 17, 12345 Musterstadt', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sSliderAutostart', 'select', 'on', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sThumbnailsize', 'str', '330*185', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sFaviconAppleFile', 'str', 'apple-touch-icon.png', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sGoogleShoppingAccountId', 'str', '', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'aNrofCatArticlesInGrid', 'arr',
        'a:4:{i:0;s:2:"12";i:1;s:2:"16";i:2;s:2:"24";i:3;s:2:"32";}', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sFavicon512PngFile', 'str', 'icon-512.png', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sDeliveryDaysOnStock', 'str', '6', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'blPrimaryColor', 'str', '#2555FF', NOW()),
       (uuid(), 1, 'theme:o3-theme', 'sShoppingCountry', 'str', 'DE', NOW());

INSERT INTO `oxconfigdisplay` (`OXID`, `OXCFGMODULE`, `OXCFGVARNAME`, `OXGROUPING`, `OXVARCONSTRAINT`, `OXPOS`, `OXTIMESTAMP`)
VALUES (uuid(), 'theme:o3-theme', 'sGATrackingId', 'googleanalytics', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'blUseGAPageTracker', 'googleanalytics', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'blGAAnonymizeIPs', 'googleanalytics', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'blUseGAEcommerceTracking', 'googleanalytics', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'sYouTubeUrl', 'footer', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sInstagramUrl', 'footer', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sFacebookUrl', 'footer', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'sTwitterUrl', 'footer', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'sGoogleMapsAddr', 'contact', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'bl_showWishlist', 'features', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'bl_showCompareList', 'features', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'bl_showListmania', 'features', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'bl_showVouchers', 'features', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'bl_showGiftWrapping', 'features', '', 5, NOW()),
       (uuid(), 'theme:o3-theme', 'bl_showPriceAlarm', 'features', '', 6, NOW()),
       (uuid(), 'theme:o3-theme', 'aDetailImageSizes', 'images', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sIconsize', 'images', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sThumbnailsize', 'images', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'sCatIconsize', 'images', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'sCatThumbnailsize', 'images', '', 5, NOW()),
       (uuid(), 'theme:o3-theme', 'sCatPromotionsize', 'images', '', 6, NOW()),
       (uuid(), 'theme:o3-theme', 'sManufacturerIconsize', 'images', '', 7, NOW()),
       (uuid(), 'theme:o3-theme', 'sZoomImageSize', 'images', '', 8, NOW()),
       (uuid(), 'theme:o3-theme', 'sSliderInterval', 'slider', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sSliderSlideFade', 'slider', 'slide|fade', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sSliderSpeed', 'slider', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'sSliderAutostart', 'slider', 'on|off', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'blEmailsShowProductPictures', 'emails', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sEmailLogo', 'logo', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sLogoFile', 'logo', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sFaviconSvgFile', 'favicons', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sFaviconAppleFile', 'favicons', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sFavicon192PngFile', 'favicons', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'sFavicon512PngFile', 'favicons', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'sFaviconIcoFile', 'favicons', '', 5, NOW()),
       (uuid(), 'theme:o3-theme', 'aNrofCatArticles', 'display', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'aNrofCatArticlesInGrid', 'display', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sDefaultListDisplayType', 'display', 'grid|line', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'blHomeLink', 'display', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'blFooterColor', 'colors', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'blPrimaryColor', 'colors', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'blSecondaryColor', 'colors', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'blFooterShowNewsletter', 'footer', '', 5, NOW()),
       (uuid(), 'theme:o3-theme', 'blFooterShowHelp', 'footer', '', 6, NOW()),
       (uuid(), 'theme:o3-theme', 'blFooterShowLinks', 'footer', '', 7, NOW()),
       (uuid(), 'theme:o3-theme', 'blFooterShowNews', 'footer', '', 8, NOW()),
       (uuid(), 'theme:o3-theme', 'sDeliveryDaysOnStock', 'googlets', '', 1, NOW()),
       (uuid(), 'theme:o3-theme', 'sDeliveryDaysNotOnStock', 'googlets', '', 2, NOW()),
       (uuid(), 'theme:o3-theme', 'sShippingDaysOnStock', 'googlets', '', 3, NOW()),
       (uuid(), 'theme:o3-theme', 'sShippingDaysNotOnStock', 'googlets', '', 4, NOW()),
       (uuid(), 'theme:o3-theme', 'sPageLanguage', 'googlets', '', 5, NOW()),
       (uuid(), 'theme:o3-theme', 'sShoppingLanguage', 'googlets', '', 6, NOW()),
       (uuid(), 'theme:o3-theme', 'sShoppingCountry', 'googlets', '', 7, NOW()),
       (uuid(), 'theme:o3-theme', 'blUseGoogleTS', 'googlets', '', 8, NOW()),
       (uuid(), 'theme:o3-theme', 'sGoogleVendorId', 'googlets', '', 9, NOW()),
       (uuid(), 'theme:o3-theme', 'sGoogleShoppingAccountId', 'googlets', '', 10, NOW());
