[{if $listDisplayType || $sort && $place != "bottom"}]
    [{if $sort}]
        [{include file="widget/locator/sort.tpl"}]
    [{/if}]

    [{if $listDisplayType}]
        [{include file="widget/locator/listdisplaytype.tpl"}]
    [{/if}]
[{/if}]

[{if $locator}]
    [{if $place == "bottom"}]
        [{include file="widget/locator/paging.tpl" pages=$locator place=$place attributes=$attributes}]
    [{/if}]
[{/if}]
